### ISSUE TITLE
HTTP GET /books?book_name=string&isbn_10=string&isbn_13=string

### ISSUE THREAD

**Issue by ssimiao** [dglsmrnh/bookquest-back#8]
Preciso de um endpoint onde eu possa consultar os livros no banco do salesforce através desses parâmetros, devolver informações básicas do livro apenas, como nome, categorias, paginas, xp, quiz habilitado, a passagem de pelo menos um campo é obrigatório

**Comment by dglsmrnh** [comment]
@PredoVin acho que seria uma boa desenvolver uma classe que faz isso, pra não ter que codar no Java

**Comment by PredoVin** [comment]
Fazer tipo um 
```
HttpResource(method='GET')
global static HttpResponse getBooks(String book_name, String isbn_10, String isbn_13) {

     //Faz a requisição na API do ISBN e retorna o resultado

}
```
?

**Comment by dglsmrnh** [comment]
Criado endpoint para consultar livros + categorias.
- verificar na pasta `Salesforce/Request/Books/Select/Multiple records/`
